version: '3.9'

services:
  app:
    container_name: ttg_bot
    environment:
      - NODE_ENV=production
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    restart: always
